- module-name: 'hdf5plugin'
  dlls:
    - from_filenames:
        relative_path: 'plugins'
        prefixes:
          - 'lib'
        suffixes:
          - 'dll'
      when: 'win32'
      dest_path: 'hdf5plugin/plugins'

- module-name: 'h5py._proxy'
  implicit-imports:
    - depends:
        - 'h5py._npystrings'
